
default_context:
    bitbucket_repo: "clique"
    bitbucket_url: "https://bitbucket.org/bitbucket-user/clique"
    bitbucket_username: "bitbucket-user"
    email: "travis@pobox.com"
    full_name: "Travis Shirk"
    github_repo: "Clique"
    github_url: "https://github.com/nicfit/Clique"
    github_username: "nicfit"
    intended_audience: "Developers"
    license: "GNU LGPL v3.0"
    project_long_description: ""
    project_name: "Clique"
    project_short_description: " Python API for Clique block chains; ID chains and auth chains included. "
    project_slug: "clique"
    py26: "no"
    py27: "no"
    py33: "no"
    py34: "no"
    py35: "yes"
    py36: "yes"
    py37: "yes"
    py_module: "clique"
    pypi_username: "nicfit"
    release_date: "today"
    src_dir: "."
    use_bitbucket: "no"
    use_github: "yes"
    use_make: "yes"
    use_paver: "no"
    use_pypi_deployment_with_travis: "no"
    use_pytest: "yes"
    use_rtd: "no"
    use_travis_ci: "yes"
    version: "0.2.0"
    web: "https://github.com/nicfit/clique"
    year: "2016-2017"
